### PR TITLE
Two fixes

### PR DESCRIPTION
**Pull request by bmwiedemann**
* Fix named_directory usage
* Sort hashes

only tested on SUSE OSes

### CODE REVIEW

**Comment by javierbertoli** [comment]
@bmwiedemann  can you add the same `|sort` parameter in the other distros' files, for consistency?

**Comment by bmwiedemann** [comment]
@javierbertoli I had already done that.

Switched to `|dictsort` now as seen in https://github.com/saltstack-formulas/munin-formula/commit/0fe2f7e66b68bebaa62247f670d43affe6cb9c96 ; also looks nicer.

There are some `iteritems()` remaining where I'm not sure, if they need treatment.

**Comment by bmwiedemann** [comment]
ping. Anything left that prevents merging?

**Comment by javierbertoli** [comment]
@bmwiedemann sorry I missed your previous comment. I think you can replace those `iteritems()` too. Would you change those, and then I'll merge, if the tests pass?

**Comment by bmwiedemann** [comment]
Did the s/iteritems/dictsort/
However, I dont know much about iterables etc in jinja/python so doing guessing here.

**Comment by javierbertoli** [comment]
@bmwiedemann , thanks to the tests introduced by @ryanwalder in #105, we can be quite sure [nothing broke](https://travis-ci.org/saltstack-formulas/bind-formula/builds/424476581), so merging :smile:

Thanks for your work!

**Pull request merged**
