### PR TITLE
Add support for custom includes on RedHat

### PR DESCRIPTION
**Pull request by mstarostik**
Trivial addition to RedHat config files to allow for custom includes

### CODE REVIEW

**Comment by javierbertoli** [comment]
@mstarostik do you consider there will be any issue moving these include lines to the `bind/files/redhat/named.conf` file, as the [debian](https://github.com/saltstack-formulas/bind-formula/blob/master/bind/files/debian/named.conf#L17-L19) and [freebsd](https://github.com/saltstack-formulas/bind-formula/blob/master/bind/files/freebsd/named.conf#L389-L391) files do?

I think that will provide more consistency to the formula behaviour among distributions.

**Comment by javierbertoli** [comment]
Mind you move it to the other file, then, for consistency-sake?

**Comment by mstarostik** [comment]
Sure thing. Just not too firm with the workflow on GitHub apparently m(

**Comment by javierbertoli** [comment]
Awesome, thanks!

**Pull request merged**
