### PR TITLE
Allow to generate zone files from pillar data

### PR DESCRIPTION
**Pull request by javierbertoli**
This PR allows to create whole zone files from data in pillar rather than just pulling the file from some location (the old behaviour is still enabled and default if no `records` entry exists for the zone).

Added some example and documentation for this feature.

A minor modification in the process of writing this:

* Debian's default user is 'bind' (it was set to `root` in `map.jinja`, causing wrong file permissions and making systemd's unit to fail because of this.

Sorry if these all seems too much in a single PR.

### CODE REVIEW

**Comment by javierbertoli** [comment]
Ping? Can you suggest another alternative reviewers?

**Comment by aboe76** [comment]
@t0fik could you take a look?

**Comment by aboe76** [comment]
merged, @t0fik thanks for the review.

**Comment by t0fik** [comment]
@aboe76 no problem, it seems to be nice feature.

**Pull request merged**
