### PR TITLE
Fix conflicts with file names. Remove hardcoded zones location.

### PR DESCRIPTION
**Pull request by ogabrielsantos**
Close issue #37 
Fix PR #28 bugs not solved (file conflicting with views and zone signer - [here](https://github.com/saltstack-formulas/bind-formula/pull/28#issuecomment-147134209), [here](https://github.com/saltstack-formulas/bind-formula/pull/28#issuecomment-147135702) and [here](https://github.com/saltstack-formulas/bind-formula/pull/28#issuecomment-147137783)). Does not inludes [`Add configuration of /detc/default/bind9 on debian systems`](https://github.com/saltstack-formulas/bind-formula/pull/28#issue-72794645).

### CODE REVIEW

**Comment by babilen** [comment]
Great! It would be wonderful if you could you rebase this a little into fewer commits on top of the master branch though.

**Comment by ogabrielsantos** [comment]
Done @babilen!

**Comment by gravyboat** [comment]
Thanks @ogabrielsantos.

**Comment by babilen** [comment]
Ta!

**Comment by ogabrielsantos** [comment]
Issue #37 can be closed.

**Comment by babilen** [comment]
@ogabrielsantos done

**Comment by hobofan** [comment]
Shouldn't the default path be `zones` instead of `/srv/salt/zones`?

If your top-level salt directory is `/srv/salt` or `/foo/bar` then that should be one of the file roots, right?
The salt file server is then responsible for figuring out where to serve the file from. I have not seen the file_root in any `salt://` url and I feel like it shouldn't be in there.

**Pull request merged**
