### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by daschatten**
* Add configuration of /detc/default/bind9 on debian systems
* Add loop index to zone file names to be able to use the same file multiple times

### CODE REVIEW

**Comment by cybacolt** [comment]
looking forward to seeing template: jinja in there...

is it worth templating a basic zone file itself as well? like so:
https://gist.github.com/abraithwaite/5e5daae2ec70f5a3312a

if this were done, there'd probably also need to be a difference between source: <template filename> and minion db.<filename> (currently the same)

**Comment by gravyboat** [comment]
@cybacolt Do you feel this should be addressed in the current PR? If not I'd like to merge this.

**Comment by ogabrielsantos** [comment]
I think that [this line should be zones-{{ file }}-{{ loop.index }}:](https://github.com/daschatten/bind-formula/blob/master/bind/config.sls#L141):
````
zones-{{ file }}-{{ loop.index }}:
  [...]

{% if args['dnssec'] is defined and args['dnssec'] -%}
signed-{{ file }}-{{ loop.index }}:
  cmd.run:
    - cwd: {{ map.named_directory }}
    - name: zonesigner -zone {{ key }} {{ file }}
    - prereq:
      - file: zones-{{ file }}-{{ loop.index }}
{% endif %}
````

[Same at L169](https://github.com/daschatten/bind-formula/blob/master/bind/config.sls#L169)

**Comment by ogabrielsantos** [comment]
Maybe two or more views sharing one zone with same file name (taking from cPanel generated DNS) [will be a issue at L147 - L174](https://github.com/daschatten/bind-formula/blob/master/bind/config.sls#L147-L174):

**Comment by ogabrielsantos** [comment]
@daschatten I can see that this is a 5 months old PR. If you don't intent to do these update I can create a new pull request including your commits and fix these new looping issues, which is a general issue.

Also I think that `bind/etcdefault.sls` should be inside `bind/config.sls` [as long as it is a configuration](https://help.ubuntu.com/community/BIND9ServerHowto#BIND9.27s_Configuration). Maybe inside [`{% if grains['os_family'] == 'Debian' %}`](https://github.com/daschatten/bind-formula/blob/master/bind/config.sls#L70-L118).

**Comment by cybacolt** [comment]
@gravyboat not a massive deal, but there is no current example of how to do this in your repo. 

would much rather see the template: jinja stuff in there before the example zone file.

i can just manage the zone file separately for now.

**Comment by gravyboat** [comment]
@cybacolt, @ogabrielsantos  Are we covered in this PR via other PRs now to an acceptable level? If not this needs to be reviewed and updated.

**Comment by cybacolt** [comment]
@gravyboat i'm happy enough, tho i may raise a seperate ticket about the zone template.

**Comment by 0xf10e** [comment]
Then let's close this PR.

**Pull request closed without merging**
