### PR TITLE
Fix some pillar paths for key "available_zones".

### PR DESCRIPTION
**Pull request by daschatten**
Fix some pillar paths for key "available_zones".

### CODE REVIEW

**Comment by gravyboat** [comment]
@daschatten Could you please modify the pillar.example to reflect this change?

**Comment by daschatten** [comment]
@gravyboat: I didn't realize that available_zones is not under the bind key. I just assumed this is a bug in the files i changed. Was there a specific reason to not put available_zones under bind?

**Comment by gravyboat** [comment]
@daschatten I have no idea to be honest, and doubt there was a reason. Some of the formulas have older styles of doing things which doesn't include nesting like we do now. What I'm talking about is just modifying: https://github.com/saltstack-formulas/bind-formula/blob/master/pillar.example#L33-L36 to be under a `bind:` section as well. I just don't want someone to fork it and get confused!

**Comment by daschatten** [comment]
Done :-)

**Comment by gravyboat** [comment]
:+1: Aww yeah! Thanks @daschatten

**Pull request merged**
