### PR TITLE
feat: implement an automated changelog

### PR DESCRIPTION
**Pull request by daks**
Before removing 'draft' status and activate only 5 builds on Travis, I wanted to test them all: Fedora and OpenSuse fails, see https://travis-ci.com/daks/bind-formula/builds/112325721.
We need to see if we can/want to fix those platforms, remove them _(in `FORMULA`, travis, kitchen, inspec)_ or just 'ignore' _ them.

**TODO**: reduce number of builds to 5 max

### CODE REVIEW

**Comment by myii** [comment]
@daks Trying to compete with @n-rodriguez to see who can do the most `semantic-release` PRs, eh?!  Maybe we should add the contributor to the docs so that we can keep track of the numbers!

**Comment by daks** [comment]
@myii, not exactly, just trying to convert all formulas we use @ work :) And this conversion is generally not that much work... except when tests start failing...

**Comment by myii** [comment]
@daks Of course, `semantic-release` isn't going to work unless all of the tests are passing, so need to ensure that that is working.  It may be worth rebasing to use the latest `Gemfile` as well.

**Comment by daks** [comment]
previous tests working: debian-8, debian-9, ubuntu-16.04, ubuntu-18.04, fedora-27 and centos-7 on latest salt

**Comment by daks** [comment]
I don't understand why those tests are failing. In theory, provisioning (states, pillars) is the same, and tests too

**Comment by daks** [comment]
I have fixed most of Suse/OpenSuse tests. The only one remaining is weird https://travis-ci.com/daks/bind-formula/jobs/202183367 -> inspec don't find 'named' service running, while it is

About Fedora, I can't fix them because they 'work on my laptop'(TM). any help would be appreciated.

**Comment by javierbertoli** [comment]
> I have fixed most of Suse/OpenSuse tests. The only one remaining is weird https://travis-ci.com/daks/bind-formula/jobs/202183367 -> inspec don't find 'named' service running, while it is

It's quite probably [the same issue](https://github.com/saltstack-formulas/template-formula/blob/master/test/integration/default/controls/services_spec.rb#L7-L10) due to [the train gem](https://github.com/inspec/train/issues/377)

Perhaps you can skip it atm.

**Comment by daks** [comment]
@javierbertoli ok, I'll sip opensuse 15 for now.

Still Fedora failing.

**Comment by myii** [comment]
@daks Or you could use @n-rodriguez's [fix here](https://github.com/saltstack-formulas/systemd-formula/pull/36/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R6) appended in the `Gemfile`:

```Ruby
gem 'train', git: 'https://github.com/n-rodriguez/train.git', branch: 'wip/fix_suse'
```

**Comment by daks** [comment]
Tests matrix reduced to 4 platforms

**Comment by myii** [comment]
@daks Do you want this merged now?

**Comment by daks** [comment]
If it's OK for everybody, yes.

**Comment by myii** [comment]
Merged, thanks for another big PR, @daks.

**Pull request merged**
